name: CI/CD - Infraestrutura

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'
      - 'developer'      
    paths:
      - '**.tf'
      - '.github/workflows/infra.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Determinar ambiente
        id: check_env
        run: |
          if [[ "${BRANCH_NAME}" == "feature/*" ]]; then
            echo "env=dev" >> $GITHUB_OUTPUT
          elif [[ "${BRANCH_NAME}" == "hotfix/*" ]]; then
            echo "env=dev" >> $GITHUB_OUTPUT
          elif [[ "${BRANCH_NAME}" == "release/*" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
          else
            echo "env=none" >> $GITHUB_OUTPUT
          fi

      - name: Encerrar se não for ambiente de deploy
        if: steps.check_env.outputs.env == 'none'
        run: echo "Branch de desenvolvimento - somente validação. Sem aplicação."

      - name: Set Azure credentials
        if: steps.check_env.outputs.env != 'none'
        run: |
          echo "ARM_CLIENT_ID=${{ secrets['ARM_CLIENT_ID_' + upper(steps.check_env.outputs.env)] }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets['ARM_CLIENT_SECRET_' + upper(steps.check_env.outputs.env)] }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets['ARM_SUBSCRIPTION_ID_' + upper(steps.check_env.outputs.env)] }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets['ARM_TENANT_ID_' + upper(steps.check_env.outputs.env)] }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Workspace Select or Create
        if: steps.check_env.outputs.env != 'none'
        run: |
          terraform workspace select ${{ steps.check_env.outputs.env }} || terraform workspace new ${{ steps.check_env.outputs.env }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: steps.check_env.outputs.env != 'none'
        run: terraform plan

      - name: Terraform Apply
        if: steps.check_env.outputs.env != 'none'
        run: terraform apply -auto-approve
